import { Visitor2Component } from './visitor2/visitor2.component';
export { TopCardComponent } from './top-card/top-card.component';
export { SalesOverviewComponent } from './sales-overview/sales-overview.component';
export { VisitorComponent } from './visitor/visitor.component';
export { VisitorUserComponent } from './visitor-user/visitor-user.component';
export { Visitor2Component } from './visitor2/visitor2.component';
export { IncomeExpenssComponent } from './income-expenss/income-expenss.component';
export { PostsComponent } from './posts/posts.component';
export { NewsletterComponent } from './newsletter/newsletter.component';
export { DeveloperInfoComponent } from './developer-info/developer-info.component';
export { ActivityComponent } from './activity/activity.component';

export { TopCard2Component } from './top-card2/top-card2.component';
export { SalesPurchaseUserComponent } from './sales-purchase-user/sales-purchase-user.component';
export { SalesPurchaseComponent } from './sales-purchase/sales-purchase.component';
export { SalesYearlyComponent } from './sales-yearly/sales-yearly.component';
export { ContactListComponent } from './contact-list/contact-list.component';
export { CommentsComponent } from './comments/comments.component';
export { MessageComponent } from './message/message.component';
